### ISSUE TITLE
Add onidle chain element into cmd-nse-icmp-responder and cover it by docker tests

### ISSUE THREAD

**Issue by d-uzlov** [networkservicemesh/cmd-nse-icmp-responder#188]
## Overview

We need to test the new `onidle` chain element.

## Implementation details

1. Add `onidle` element into responder endpoint chain, and configure it to stop the server on callback.
2. Add timeout parameter to server config.
Timeout should be defined as a pointer in the config to allow to determine whether the corresponding environment variable is set. If env variable was not set, then we shouldn't add the element.
3. Add a test that checks that the server successfully dies on specified timeout.

## References

https://github.com/networkservicemesh/sdk/issues/892

**Comment by edwarnicke** [comment]
It seems like the simplest way here is to simply have onidle.NewServer interpret a timeout of 0 as 'no timeout' and return null.NewServer ... that way we can set an NSM_ONIDLE_TIMEOUT env variable with default 0 and things work as normal unless its set, and if it is set, we get the onidle behavior.  Thoughts?
