### ISSUE TITLE
Add env `GROUP_ID` to endpoints

### ISSUE THREAD

**Issue by Mixaster995** [networkservicemesh/cmd-nse-icmp-responder#358]
## Description
For supporting mutually aware `NSEs` add env variable `GROUP_ID` which defaults to empty string

## Issue
part of https://github.com/networkservicemesh/api/issues/121

## Definition of done
- Add field `groupID` to config for all nse `cmd`
- Add this field to connection according to changes here https://github.com/networkservicemesh/sdk/issues/1203
- Test that variable setting works correctly

**Comment by NikitaSkrynnik** [comment]
This PR is not needed anymore. The feature has been implemented here: https://github.com/networkservicemesh/api/issues/121
