### ISSUE TITLE
Group IPAM conflicts with strict policy

### ISSUE THREAD

**Issue by Ex4amp1e** [networkservicemesh/cmd-nse-icmp-responder#614]
Steps to reproduce:
Configure envs on endpoint
```
        - name: NSM_IPAM_POLICY
          value: strict
        - name: NSM_CIDR_PREFIX
          value: 172.16.1.100/27,2001:db8::/116
```

Actual: only ipv6 pool is configured on client and endpoint. Healing is not working after endpoint and registry restart.

Expected: 2 ip pools, healing works well.

Solution:
Place IPAM policy over group policy

**Comment by NikitaSkrynnik** [comment]
Group IPAM: https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/ipam/groupipam/server.go
Strict IPAM: https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/ipam/strictipam/server.go
They are used here: https://github.com/networkservicemesh/cmd-nse-icmp-responder/blob/main/main.go#L248
